CREATE TABLE `CollectibleIncomeItems` (
  `itemId` INTEGER NOT NULL AUTO_INCREMENT,
  `companyId` INTEGER NOT NULL,
  `testName` VARCHAR(255) NOT NULL,
  `unitPrice` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `quantity` INTEGER NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`itemId`),
  FOREIGN KEY (`companyId`) REFERENCES `CollectibleIncome`(`companyId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
